### ISSUE TITLE
Docker compose needs to create postgis database and do initial migration

### ISSUE THREAD

**Issue by destos** [tulsawebdevs/tulsawebdevs.org#13]
@jgmize would you have time to look into this at some point? I got the docker dev build most of the way there with django running, just can't figure out how to create the database.

This may be relevant:
https://stackoverflow.com/questions/31644175/docker-compose-postgres-customize-database-details

**Comment by destos** [comment]
related to #9

**Comment by jgmize** [comment]
@destos do you really need post*gis* or did you mean post*gres*?

**Comment by destos** [comment]
@jgmize, I would like to use some gis features in the API, and have already done so in storing event locations.
