### ISSUE TITLE
First install issue with webpack

### ISSUE THREAD

**Issue by nearbycoder** [tulsawebdevs/tulsawebdevs.org#17]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.4/site-packages/whitenoise/base.py", line 119, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 261, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/local/lib/python3.4/site-packages/django_extensions/management/technical_response.py", line 5, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/site-packages/six.py", line 659, in reraise
    raise value
  File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/usr/local/lib/python3.4/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.4/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/usr/local/lib/python3.4/site-packages/django_jinja/backend.py", line 64, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.4/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.4/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/app/twd/templates/twd/home.jinja", line 1, in top-level template code
    {% extends "layout.jinja" %}
  File "/app/twd/templates/layout.jinja", line 15, in top-level template code
    {{ render_bundle('main') }}
  File "/usr/local/lib/python3.4/site-packages/webpack_loader/contrib/jinja2ext.py", line 9, in <lambda>
    environment.globals["render_bundle"] = lambda *a, **k: jinja2.Markup(render_bundle(*a, **k))
  File "/usr/local/lib/python3.4/site-packages/webpack_loader/templatetags/webpack_loader.py", line 29, in render_bundle
    bundle = get_bundle(bundle_name)
  File "/usr/local/lib/python3.4/site-packages/webpack_loader/utils.py", line 47, in get_bundle
    assets = get_assets()
  File "/usr/local/lib/python3.4/site-packages/webpack_loader/utils.py", line 33, in get_assets
    'the file and the path is correct?'.format(config['STATS_FILE']))
OSError: Error reading /app/twd/assets/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?

**Comment by destos** [comment]
Can you try running `docker-compose run web npm run build` that should run the webpack build process. Which should be run when docker builds the initial container… Will have to investigate why It didn't do that.

**Comment by nearbycoder** [comment]
fixed the issue. I just ran npm install in the directory and then docker-compose up -d

**Comment by destos** [comment]
Could you post the console out put of the initial docker compose up? Interested in seeing what went wrong. You may have had an old checkout.



—
Patrick Forringer

**Comment by nearbycoder** [comment]
I did docker logs container  hope thats what you wanted and here it is

CREATE EXTENSION
Operations to perform:
  Synchronize unmigrated apps: webpack_loader, django_extensions, staticfiles, rest_framework, debug_toolbar, recurrence, rest_framework_gis, twd, messages, gis, api, mptt
  Apply all migrations: auth, talks, events, admin, contenttypes, sessions
Synchronizing apps without migrations:
  Creating tables...
    Creating table recurrence_recurrence
    Creating table recurrence_rule
    Creating table recurrence_date
    Creating table recurrence_param
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying events.0001_initial... OK
  Applying events.0002_auto_20150815_1837... OK
  Applying sessions.0001_initial... OK
  Applying talks.0001_initial... OK
  Applying talks.0002_auto_20150808_2108... OK
  Applying talks.0003_auto_20150816_2148... OK
Validating models...
System check identified no issues (0 silenced).

Django version 1.8.4, using settings 'config'
Development server is running at http://0.0.0.0:8000/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CONTROL-C.
Validating models...
System check identified no issues (0 silenced).

Django version 1.8.4, using settings 'config'
Development server is running at http://0.0.0.0:8000/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CONTROL-C.
Operations to perform:
  Synchronize unmigrated apps: messages, django_extensions, gis, webpack_loader, staticfiles, mptt, rest_framework_gis, api, rest_framework, recurrence, debug_toolbar, twd
  Apply all migrations: admin, events, auth, sessions, contenttypes, talks
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Validating models...
System check identified no issues (0 silenced).

Django version 1.8.4, using settings 'config'
Development server is running at http://0.0.0.0:8000/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CONTROL-C.
Validating models...
System check identified no issues (0 silenced).

Django version 1.8.4, using settings 'config'
Development server is running at http://0.0.0.0:8000/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CONTROL-C.
Operations to perform:
  Synchronize unmigrated apps: webpack_loader, rest_framework_gis, staticfiles, mptt, rest_framework, api, django_extensions, recurrence, twd, debug_toolbar, messages, gis
  Apply all migrations: contenttypes, events, auth, admin, sessions, talks
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Validating models...
System check identified no issues (0 silenced).

Django version 1.8.4, using settings 'config'
Development server is running at http://0.0.0.0:8000/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CONTROL-C.
Validating models...
System check identified no issues (0 silenced).

Django version 1.8.4, using settings 'config'
Development server is running at http://0.0.0.0:8000/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CONTROL-C.
Operations to perform:
  Synchronize unmigrated apps: mptt, staticfiles, rest_framework_gis, twd, gis, webpack_loader, django_extensions, debug_toolbar, api, messages, rest_framework, recurrence
  Apply all migrations: admin, contenttypes, auth, events, sessions, talks
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Validating models...
System check identified no issues (0 silenced).

Django version 1.8.4, using settings 'config'
Development server is running at http://0.0.0.0:80/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CONTROL-C.
Validating models...
System check identified no issues (0 silenced).

Django version 1.8.4, using settings 'config'
Development server is running at http://0.0.0.0:80/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CONTROL-C.
Operations to perform:
  Synchronize unmigrated apps: recurrence, django_extensions, debug_toolbar, staticfiles, webpack_loader, rest_framework, rest_framework_gis, messages, twd, api, gis, mptt
  Apply all migrations: events, auth, talks, contenttypes, sessions, admin
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Validating models...
System check identified no issues (0 silenced).

Django version 1.8.4, using settings 'config'
Development server is running at http://0.0.0.0:8000/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CONTROL-C.
Validating models...
System check identified no issues (0 silenced).

Django version 1.8.4, using settings 'config'
Development server is running at http://0.0.0.0:8000/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CONTROL-C.
Operations to perform:
  Synchronize unmigrated apps: gis, mptt, webpack_loader, messages, rest_framework_gis, debug_toolbar, django_extensions, api, rest_framework, staticfiles, twd, recurrence
  Apply all migrations: talks, contenttypes, sessions, events, admin, auth
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Validating models...
System check identified no issues (0 silenced).

Django version 1.8.4, using settings 'config'
Development server is running at http://0.0.0.0:8000/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CONTROL-C.
Validating models...
System check identified no issues (0 silenced).

Django version 1.8.4, using settings 'config'
Development server is running at http://0.0.0.0:8000/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CONTROL-C.
Operations to perform:
  Synchronize unmigrated apps: messages, django_extensions, twd, api, mptt, rest_framework_gis, staticfiles, webpack_loader, rest_framework, debug_toolbar, gis, recurrence
  Apply all migrations: contenttypes, sessions, admin, events, auth, talks
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Validating models...
System check identified no issues (0 silenced).

Django version 1.8.4, using settings 'config'
Development server is running at http://0.0.0.0:8000/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CONTROL-C.
Validating models...
System check identified no issues (0 silenced).

Django version 1.8.4, using settings 'config'
Development server is running at http://0.0.0.0:8000/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CONTROL-C.
Operations to perform:
  Synchronize unmigrated apps: rest_framework, rest_framework_gis, webpack_loader, mptt, twd, staticfiles, recurrence, api, messages, debug_toolbar, gis, django_extensions
  Apply all migrations: admin, contenttypes, events, auth, talks, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Validating models...
System check identified no issues (0 silenced).

Django version 1.8.4, using settings 'config'
Development server is running at http://0.0.0.0:8000/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CONTROL-C.
Validating models...
System check identified no issues (0 silenced).

Django version 1.8.4, using settings 'config'
Development server is running at http://0.0.0.0:8000/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CONTROL-C.
Operations to perform:
  Synchronize unmigrated apps: staticfiles, twd, gis, rest_framework, api, recurrence, rest_framework_gis, messages, webpack_loader, mptt, django_extensions, debug_toolbar
  Apply all migrations: admin, contenttypes, sessions, events, auth, talks
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
Validating models...
System check identified no issues (0 silenced).

Django version 1.8.4, using settings 'config'
Development server is running at http://0.0.0.0:8000/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CONTROL-C.
Validating models...
System check identified no issues (0 silenced).

Django version 1.8.4, using settings 'config'
Development server is running at http://0.0.0.0:8000/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CONTROL-C.

**Comment by destos** [comment]
Chalking this up as an outdated git repo issue.
