### ISSUE TITLE
tulsawebdevs.org returning 403 Forbidden error

### ISSUE THREAD

**Issue by sergei202** [tulsawebdevs/tulsawebdevs.org#27]
Not sure if you guys are in the middle of updating something, but getting a 403 error trying to access the homepage of http://tulsawebdevs.org:

![image](https://cloud.githubusercontent.com/assets/15058464/11538512/f26a0d2e-98e7-11e5-9093-64362b100287.png)

**Comment by destos** [comment]
Thanks for reporting this. It's currently a WordPress site that's experiencing issues. The person who's hosting the site had been notified.

—
Patrick Forringer

**Comment by kendallwerts** [comment]
:-1: 403 again
